//--------------------------------------------------------------
//--------------E-PROOF-BACKGROUND-CODE 1:----------------------
//--------------------------------------------------------------
//---BEGIN: eProofJS.js Generator
$vOut="//--------------------------------------------\n"
$vOut.="var vQID = vSettings[\"vQID\"];\n"
$vOut.="var ThisQ = vSettings[\"ThisQ\"];\n"
$vOut.="var vLink_Screencast = \"http://e-proof.weebly.com/german-tutorials.html\";\n"
$vOut.="var vLink_Tutorial   = \"http://math.uni-landau.de/download/IMathAS/eProof_iMathAS_Tutorial.pdf\";\n"
$vOut.="var vMaxQuestionPart = 6;\n"
$vOut.="var vUpdateEdit = 0;\n"
$vOut.="var CR = String.fromCharCode(10); //newline symbol /n\n"
$vOut.="var GT = String.fromCharCode(62); //greater than symbol >\n"
$vOut.="var LT = String.fromCharCode(60); //lower than symbol >\n"
$vOut.="var AP = String.fromCharCode(96); //IMathAS Apostrophe\n"
$vOut.="var vStepMap  = new Array();\n"
$vOut.="var vEditorID = \"XmceEditor\";\n"
$vOut.="var vUpdateButton = \"<input type='button' name='bUpdate\"+vQID+\"' value=' Update ' onclick=\\\"updateInput2IMathAS(this.form)\\\">\";\n"
$vOut.="var vSpace =  \" &nbsp;&nbsp; \" \n"
$vOut.="var vConnection2Index = new Array();\n"
$vOut.="var vConnectionArray = new Array(\"???\",\"TYP\",\" \",\"=\"+GT,\"=\",LT+\"=\",LT,GT+\"=\",GT,\"subseteq\",\"DEF\",\"TEXT\",\"q.e.d.\");\n"
$vOut.="var vNr = 1;\n"
$vOut.="vConnection2Index[\"TYP\"] = vNr;\n"
$vOut.="vNr++;\n"
$vOut.="vConnection2Index[\" \"] = vNr; //START: Beweissequenz\n"
$vOut.="vNr++;\n"
$vOut.="vConnection2Index[\"=\"+GT] = vNr;\n"
$vOut.="vNr++;\n"
$vOut.="vConnection2Index['='] = vNr;\n"
$vOut.="vNr++;\n"
$vOut.="vConnection2Index[LT+\"=\"] = vNr;\n"
$vOut.="vNr++;\n"
$vOut.="vConnection2Index[LT] = vNr;\n"
$vOut.="vNr++;\n"
$vOut.="vConnection2Index[GT+'='] = vNr;\n"
$vOut.="vNr++;\n"
$vOut.="vConnection2Index[GT] = vNr;\n"
$vOut.="vNr++;\n"
$vOut.="vConnection2Index['subseteq'] = vNr;\n"
$vOut.="vNr++;\n"
$vOut.="vConnection2Index['DEF'] = vNr;\n"
$vOut.="vNr++;\n"
$vOut.="vConnection2Index['TEXT'] = vNr;\n"
$vOut.="vNr++;\n"
$vOut.="vConnection2Index['q.e.d.'] = vNr;\n"
$vOut.="function appendNewStep(pMaxSteps) {\n"
$vOut.="  var vNewNodeID = document.getElementById(\"newSTEP\"+vQID);\n"
$vOut.="  if (vNewNodeID) {\n"
$vOut.="    var vID = vNewNodeID.value;\n"
$vOut.="    if (vID.indexOf(\"?\") == 0) {\n"
$vOut.="      var iIndex = getStepIndex4ID(vID);\n"
$vOut.="      if (iIndex == -1) {\n"
$vOut.="        alert(\"ID '\"+vID+\"' does not exist in e-Proof!\");\n"
$vOut.="      } else {\n"
$vOut.="        moveStep(iIndex,pMaxSteps);\n"
$vOut.="      }\n"
$vOut.="    } else {\n"
$vOut.="      alert(\"vNewNodeID.value='???' no append\");\n"
$vOut.="    }\n"
$vOut.="  } else {\n"
$vOut.="    alertDOM(\"DOM-Node 'newSTEP\"+vQID+\" does not exist! - appendNewStep()-Call\");\n"
$vOut.="  }\n"
$vOut.="}\n"
$vOut.="function updateNewStep(pMaxSteps) {\n"
$vOut.="  var vNewNodeID = document.getElementById(\"newSTEP\"+vQID);\n"
$vOut.="  var vStudentAnswerList = document.getElementsByClassName(\"STUDENTANSWER\"+vQID);\n"
$vOut.="  if (vNewNodeID) {\n"
$vOut.="    var vID = vNewNodeID.value;\n"
$vOut.="    if (vID.indexOf(\"?\") == 0) {\n"
$vOut.="      var iIndex = getStepIndex4ID(vID);\n"
$vOut.="      if (iIndex == -1) {\n"
$vOut.="        alert(\"ID '\"+vID+\"' does not exist in e-Proof!\");\n"
$vOut.="      } else {\n"
$vOut.="        var vStudentAnswer = vStudentAnswerList[iIndex-1];\n"
$vOut.="        var vEditStudentAnswer = vStudentAnswer.getElementsByClassName(\"editSTUDENTANSWER\"+vQID)[0];\n"
$vOut.="        var vNodeID   = vEditStudentAnswer.getElementsByClassName(\"sSTEP\"+vQID)[0]; \n"
$vOut.="        var vNodeCon  = vEditStudentAnswer.getElementsByClassName(\"sCONNECTION\"+vQID)[0]; \n"
$vOut.="        var vNodeJust = vEditStudentAnswer.getElementsByClassName(\"inJUSTIFICATION\"+vQID)[0]; \n"
$vOut.="        var vNewNodeID   = document.getElementsByClassName(\"newsSTEP\"+vQID)[0]; \n"
$vOut.="        var vNewNodeCon  = document.getElementsByClassName(\"newsCONNECTION\"+vQID)[0]; \n"
$vOut.="        var vNewNodeJust = document.getElementsByClassName(\"newinJUSTIFICATION\"+vQID)[0]; \n"
$vOut.="        moveStep(iIndex,pMaxSteps);\n"
$vOut.="      }\n"
$vOut.="    } else {\n"
$vOut.="      alert(\"vNewNodeID.value='???' no append\");\n"
$vOut.="    }\n"
$vOut.="  } else {\n"
$vOut.="    alertDOM(\"DOM-Node 'newSTEP\"+vQID+\" does not exist! - appendNewStep()-Call\");\n"
$vOut.="  }\n"
$vOut.="}\n"
$vOut.="function getStudentAnswerHTML() {\n"
$vOut.="  var vListArray = new Array();\n"
$vOut.="  var vCount = 0;\n"
$vOut.="  var vAllSteps = new Array();\n"
$vOut.="  var vID = \"\";\n"
$vOut.="  var vStepDef = \"\";\n"
$vOut.="  var vList = null; \n"
$vOut.="  vListArray.push(document.getElementsByClassName(\"PRECONDITION\"+vQID));\n"
$vOut.="  vListArray.push(document.getElementsByClassName(\"PROOFSTEP\"+vQID));\n"
$vOut.="  vListArray.push(document.getElementsByClassName(\"CONCLUSION\"+vQID));\n"
$vOut.="  var k=0;\n"
$vOut.="  var j=0;\n"
$vOut.="  while (lower(k,vListArray.length)) {\n"
$vOut.="    vList = vListArray[k];\n"
$vOut.="    vCount += vList.length;\n"
$vOut.="    j=0;\n"
$vOut.="    while (lower(j,vList.length)) if (vList[j].id) {\n"
$vOut.="      vID = vList[j].id;\n"
$vOut.="      vStepDef = vList[j].childNodes[0].nodeValue;\n"
$vOut.="      vAllSteps[vID] = vStepDef;\n"
$vOut.="      j++;\n"
$vOut.="    };\n"
$vOut.="    k++;\n"
$vOut.="  };\n"
$vOut.="  var vStart = 0;\n"
$vOut.="  var vContent = \"\";\n"
$vOut.="  vContent += \"<DIV class='STUDENTANSWERLIST\"+vQID+\"' id='STUDENTANSWERLIST\"+vQID+\"'>\";\n"
$vOut.="  var vJustList = document.getElementsByClassName(\"JUSTIFICATION\"+vQID);\n"
$vOut.="  k=0;\n"
$vOut.="  while (lower(k,vListArray.length)) {\n"
$vOut.="    vContent += getAnswerItemHTML(vListArray[k],vJustList,vStart,vCount,vAllSteps);\n"
$vOut.="    vStart += vListArray[k].length;\n"
$vOut.="    k++;\n"
$vOut.="  }\n"
$vOut.="  vContent +=\"</DIV>\";\n"
$vOut.="  return vContent;\n"
$vOut.="}\n"
$vOut.="function getAnswerHeaderHTML() {\n"
$vOut.="  var vShow_Links = getSetting(\"show_links\");\n"
$vOut.="  var vContent = \"\";\n"
$vOut.="  vContent += \"<hr><table align=\\\"center\\\"><tbody><tr>\";\n"
$vOut.="  vContent += \"<td><b>\" +vLanguage[\"Number_of\"]+\" \"+vLanguage[\"ProofSteps\"]+\":</b></td>\";\n"
$vOut.="    vContent += \"<td>\" + getStepCountSelectorHTML() + \"</td>\"\n"
$vOut.="    vContent += \"<td>\" + \" \" +\"</td>\";\n"
$vOut.="    if (vShow_Links != \"0\") {\n"
$vOut.="       vContent += \"<td>\";\n"
$vOut.="       vContent += \"<a href=\\\"\"+vLink_Tutorial+\"\\\" target=\\\"_blank\\\">PDF-Tutorial</a>\"\n"
$vOut.="     vContent += \"</td>\";\n"
$vOut.="   }\n"
$vOut.="     vContent += \"</tr><tr>\";\n"
$vOut.="     vContent += \"</tr><tr>\";\n"
$vOut.="  vContent += \"<tr><td><b>\" +vLanguage[\"Display\"]+\" \"+vLanguage[\"Proof\"]+\":</b>\";\n"
$vOut.="    vContent += \"<td><SELECT id='sDISPLAYOPTION\"+vQID+\"' onchange=\\\"setVisibility4Proof(this.value,this.form)\\\">\"\n"
$vOut.="    vContent += \"<OPTION value='Complete' >EDIT: \"+vLanguage[\"Complete\"]+\"</OPTION>\";\n"
$vOut.="    vContent += \"<OPTION value='Short'>EDIT: \"+vLanguage[\"Short\"]+\"</OPTION>\";\n"
$vOut.="    vContent += \"<OPTION value='Hide'>EDIT: \"+vLanguage[\"Hide\"]+\"</OPTION>\";\n"
$vOut.="    if (getSetting(\"show_feedback_score\") != \"0\") {\n"
$vOut.="      vContent += \"<OPTION value='Assessment'>\"+vLanguage[\"Assessment\"]+\"</OPTION>\";\n"
$vOut.="    };\n"
$vOut.="     if (getSetting(\"show_proof_solution\") != \"0\") {\n"
$vOut.="      vContent += \"<OPTION value='Solution'>\"+vLanguage[\"Solution\"]+\"</OPTION>\";\n"
$vOut.="    };\n"
$vOut.="     vContent += \"</SELECT></td>\";\n"
$vOut.="  vContent += \"<td>\" + vUpdateButton +\"</td>\";\n"
$vOut.="    if (vShow_Links != \"0\") {\n"
$vOut.="       vContent += \"<td>\";\n"
$vOut.="       vContent += \"<a href=\\\"\"+vLink_Screencast+\"\\\" target=\\\"_blank\\\">Video/Screencast</a>\"\n"
$vOut.="     vContent += \"</td>\";\n"
$vOut.="   }\n"
$vOut.="  vContent += \"</tr><tr>\";\n"
$vOut.="  vContent += \"</tr></tbody></table><hr>\";\n"
$vOut.="  return vContent;\n"
$vOut.="}\n"
$vOut.="function getAnswerItemHTML(pList,pJustList,pNrStart,pCount,pAllSteps) {\n"
$vOut.="  var vName = \"\";\n"
$vOut.="  var vContent = \"\";\n"
$vOut.="  var vNr=pNrStart;\n"
$vOut.="  var k=0;\n"
$vOut.="  while (lower(k,pList.length)) if (pList[k].id) {\n"
$vOut.="      vNr++;\n"
$vOut.="      vStepMap[\"STUDENTANSWER\"+vNr] = vNr;\n"
$vOut.="    vContent += \"<DIV class='STUDENTANSWER\"+vQID+\"' id='STUDENTANSWER\"+vQID+vNr+\"' step='\"+vNr+\"' >\";\n"
$vOut.="    vContent += \"<DIV class='editSTUDENTANSWER\"+vQID+\"' id='editSTUDENTANSWER\"+vQID+vNr+\"'>\";\n"
$vOut.="    vContent += setStepPosition(vNr,pCount);\n"
$vOut.="    vContent += \"<input type='button' class='bUseStep\"+vQID+\"' step='\"+vNr+\"'  id='bUseStep\"+vQID+vNr+\"' value=' + ' onclick=\\\"appendStep(\"+vNr+\")\\\" style='visibility:hidden' />\"; //style='visibility:hidden'\n"
$vOut.="    vContent += setStepConnection(vNr,pCount);\n"
$vOut.="    vContent += \"<input type='button' class='bEdit\"+vQID+\"' step='\"+vNr+\"'  id='bEdit\"+vQID+vNr+\"'  value=' EDIT ' onclick=\\\"toggleEdit(\"+vNr+\")\\\" />\";\n"
$vOut.="    vContent += setStepDefinition(vNr,pCount,pAllSteps,pList[k].id);\n"
$vOut.="    vContent += \"<input type='button' class='bDelete\"+vQID+\"' step='\"+vNr+\"'  id='bDelete\"+vQID+vNr+\"' value=' X ' onclick=\\\"deleteProofStep(\"+vNr+\",\"+pCount+\")\\\" style='color:red'/>\";\n"
$vOut.="    vName = \"cVIEWJUSTIFICATION\"+vQID;\n"
$vOut.="    vContent += \"<input type='checkbox' class='\"+vName+\"' name='\"+vName+vNr+\"' step='\"+vNr+\"' id='\"+vName+vNr+\"' value='VIEW' onchange=\\\"changeViewJustification(\"+vNr+\")\\\" checked='checked' style='display:none'/> \"; // style='visibility:hidden'\n"
$vOut.="    vName = \"cEDITJUSTIFICATION\"+vQID;\n"
$vOut.="    vContent += \"<input type='checkbox' class='\"+vName+\"' name='\"+vName+vNr+\"' step='\"+vNr+\"' id='\"+vName+vNr+\"' value='EDIT' onchange=\\\"changeViewJustification(\"+vNr+\")\\\" style='display:none' /> \"; //style='display:none'\n"
$vOut.="    vContent += \"<input type='button' class='bJUSTIFICATION\"+vQID+vNr+\"' step='\"+vNr+\"'  id='bJUSTIFICATION\"+vQID+vNr+\"' value='\"+ vLanguage[\"Justifications\"]+\"'onclick=\\\"toggleJustification(\"+vNr+\")\\\" />\";\n"
$vOut.="    vContent += \"<input type='text' size='15' class='inJUSTIFICATION\"+vQID+\"' step='\"+vNr+\"' id='inJUSTIFICATION\"+vQID+vNr+\"' value='' onchange=\\\"changeEditJustification(\"+vNr+\")\\\"/>\";\n"
$vOut.="    vContent += \"<input class=\\\"inSTEPID\"+vQID+\"\\\" type='text' size='3'  step='\"+vNr+\"' id='inSTEPID\"+vQID+vNr+\"'  value=\\\"\"+pList[k].id+\"\\\" style='display:none' />\"; // style='display:none' style='visibility:hidden'\n"
$vOut.="    vContent += \"<input class=\\\"STEP\"+vQID+\"\\\" type='text' size='3'  value='\"+vNr+\"' id='STEP\"+vQID+vNr+\"' style='display:none' />\"; // style='display:none' style='visibility:hidden'\n"
$vOut.="    vContent += \"<DIV class='STEPEDITOR\"+vQID+\"' id='STEPEDITOR\"+vQID+vNr+\"' style='display:none'>\"; \n"
$vOut.="    vContent += \"<textarea rows='9' class=\\\"\"+ vEditorID + vQID+\"\\\" id='\"+ vEditorID +vQID+ +vNr+\"' style='width:98%;'  onkeyup=\\\"updateTextarea(\"+vNr+\")\\\" ></textarea>\";\n"
$vOut.="    vContent += \"<input class=\\\"inSTEPDEF\"+vQID+\"\\\" type='text' size='92' step='\"+vNr+\"' id='inSTEPDEF\"+vQID+vNr+\"'  value=\\\"\"+pList[k].childNodes[0].nodeValue+\"\\\"  onchange=\\\"updateStepEdit(\"+vNr+\")\\\" />\";\n"
$vOut.="    vContent += \"<br/>\"+vUpdateButton+\"</DIV>\";\n"
$vOut.="    vContent += \"</DIV>\";\n"
$vOut.="    vContent += \"<DIV class='outIDandSTEP\"+vQID+\"' id='outIDandSTEP\"+vQID+vNr+\"'>\";\n"
$vOut.="    vContent +=\"<OUTSTEP class='outSTEP\"+vQID+\"' id='outSTEP\"+vQID+vNr+\"' style='display:none'>\";\n"
$vOut.="    vContent += \"(\"+vNr+\") \"+vSpace;\n"
$vOut.="    vContent += AP+\"???\"+AP+\" \"+ vSpace + getStepDef(pList[k]);\n"
$vOut.="    vContent +=\"</OUTSTEP>\";\n"
$vOut.="    vContent += getStepDiplayHTML(pAllSteps,vNr,pCount);\n"
$vOut.="    vContent +=\"</DIV>\";\n"
$vOut.="    vContent +=\"<DIV class='dVIEWJUSTIFICATION\"+vQID+\"' id='dVIEWJUSTIFICATION\"+vQID+vNr+\"' style='display:none' >\";\n"
$vOut.="    vContent += getJustificationHTML(pJustList,pAllSteps,vNr,pCount);\n"
$vOut.="    vContent +=\"</DIV>\";\n"
$vOut.="    vContent +=\"<DIV class='dEDITJUSTIFICATION\"+vQID+\"' id='dEDITJUSTIFICATION\"+vQID+vNr+\"' style='display:none' >\";\n"
$vOut.="    vContent += getJustificationCheckboxHTML(pJustList,pAllSteps,vNr,pCount);\n"
$vOut.="    vContent +=\"</DIV>\";\n"
$vOut.="    vContent +=\"</DIV>\";\n"
$vOut.="    k++;\n"
$vOut.="  };\n"
$vOut.="  return vContent;\n"
$vOut.="}\n"
$vOut.="function setStepPosition(pStep,pCount) {\n"
$vOut.="  var vName = \"sPOSITION\"+vQID;\n"
$vOut.="  var vDeleteName = \"DEL\";\n"
$vOut.="  var vNr = 0;\n"
$vOut.="  var vContent = \"<SELECT class='\"+vName+\"' step='\"+pStep+\"'  id='\"+vName+pStep+\"' onchange=\\\"positionChange(\"+pStep+\",this.value,\"+pCount+\")\\\">\";\n"
$vOut.="  while (lower(vNr,pCount)) {\n"
$vOut.="    vNr++;\n"
$vOut.="    if (pStep != vNr) {\n"
$vOut.="    vContent +=\"<OPTION VALUE='\"+vNr+\"'>\"+vNr+\"</OPTION>\";\n"
$vOut.="    } else {\n"
$vOut.="    vContent +=\"<OPTION VALUE='\"+vNr+\"' selected='selected'>\"+vNr+\"</OPTION>\";\n"
$vOut.="    }\n"
$vOut.="  };\n"
$vOut.="  vContent +=\"</SELECT>\";\n"
$vOut.="  return vContent;\n"
$vOut.="}\n"
$vOut.="function setStepConnection(pStep,pCount) {\n"
$vOut.="  var vName = \"sCONNECTION\"+vQID;\n"
$vOut.="  var vDeleteName = \"DEL\";\n"
$vOut.="  var vContent = \"<SELECT  class='\"+vName+\"' step='\"+pStep+\"' id='\"+vName+pStep+\"'  onchange=\\\"updateStep(\"+pStep+\")\\\">\";\n"
$vOut.="  vContent +=\"<option value='0'>\"+vLanguage[\"Connection\"] + \"?</option>\";\n"
$vOut.="  vContent +=\"<option value='1'>\"+vLanguage[\"Type\"] + \"</option>\";\n"
$vOut.="  vContent +=\"<option value='2'>START: \"+vLanguage[\"ProofSequence\"] + \"</option>\";\n"
$vOut.="  vContent +=\"<option value='3'>\"+vLanguage[\"Implication\"] + \"</option>\";\n"
$vOut.="  vContent +=\"<option value='4'>\"+vLanguage[\"Equality\"] + \"</option>\";\n"
$vOut.="  vContent +=\"<option value='5'>\"+vLanguage[\"lower_equal\"] + \"</option>\";\n"
$vOut.="  vContent +=\"<option value='6'>\"+vLanguage[\"lower\"] + \"</option>\";\n"
$vOut.="  vContent +=\"<option value='7'>\"+vLanguage[\"greater_equal\"] + \"</option>\";\n"
$vOut.="  vContent +=\"<option value='8'>\"+vLanguage[\"greater\"] + \"</option>\";\n"
$vOut.="  vContent +=\"<option value='9'>\"+vLanguage[\"Subset\"] + \"</option>\";\n"
$vOut.="  vContent +=\"<option value='10'>Definition \" + vLanguage[\"of\"] + \" \"+ vLanguage[\"Variables\"] + \"</option>\";\n"
$vOut.="  vContent +=\"<option value='11'>Text \"+vLanguage[\"or\"] + \" \"+ vLanguage[\"Comment\"] + \"</option>\";\n"
$vOut.="  vContent +=\"<option value='12'>q.e.d.</option>\";\n"
$vOut.="  vContent +=\"</SELECT>\";\n"
$vOut.="  return vContent;\n"
$vOut.="}\n"
$vOut.="function setStepDefinition(pStep,pCount,pAllSteps,pSelectedID) {\n"
$vOut.="  var vName = \"sSTEP\"+vQID;\n"
$vOut.="  var vContent = \"<SELECT class='\"+vName+\"' step='\"+pStep+\"' id='\"+vName+pStep+\"' onchange=\\\"moveStepID(\"+pStep+\",this.value,\"+pCount+\")\\\" >\";\n"
$vOut.="  for (var iID in pAllSteps) {\n"
$vOut.="      if (pSelectedID != iID) {\n"
$vOut.="      vContent +=\"<option class='OPTION_\"+iID+\"' value='\"+iID+\"'>\"+iID+\"</option>\";\n"
$vOut.="    } else {\n"
$vOut.="      vContent +=\"<option class='OPTION_\"+iID+\"' value='\"+iID+\"' selected='selected'>\"+iID+\"</option>\";\n"
$vOut.="    }\n"
$vOut.="    }\n"
$vOut.="  vContent +=\"</SELECT>\";\n"
$vOut.="  return vContent;\n"
$vOut.="}\n"
$vOut.="function getStepDiplayHTML(pAllSteps,pStep,pCount) {\n"
$vOut.="  var vCellWidth = \"40px\";\n"
$vOut.="  var vContent = \"<table width='95%'border='0'><tr><td valign='center'  width='\"+vCellWidth+\"'>\";\n"
$vOut.="  var vName = \"outSTEPDISPLAY\"+vQID+pStep; \n"
$vOut.="  var vID = \"\";\n"
$vOut.="  var vHideShow = \"style=\\\"display:none\\\"\"\n"
$vOut.="  var i = 0;\n"
$vOut.="  for (var vID in pAllSteps) {\n"
$vOut.="    i++;\n"
$vOut.="    if (i == pStep) {\n"
$vOut.="      vHideShow = \"style=\\\"display:block\\\"\";\n"
$vOut.="    } else {\n"
$vOut.="      vHideShow = \"style=\\\"display:none\\\"\";\n"
$vOut.="    }\n"
$vOut.="    vContent += \"<OUTTEXT class='\"+vName+\"' id='\"+vName+\"-POS-\"+i+\"' \"+vHideShow+\">(\"+i+\")</OUTTEXT>\";\n"
$vOut.="  };\n"
$vOut.="  vContent += vSpace+\"</td><td valign='center'  width='\"+vCellWidth+\"'>\";\n"
$vOut.="  vHideShow = \"style=\\\"display:block\\\"\";\n"
$vOut.="  vContent += \"<OUTTEXT class='\"+vName+\"' id='\"+vName+\"-CON-0'  \"+vHideShow+\">\"+AP+ \"???\" + AP +\"</OUTTEXT>\";\n"
$vOut.="  vHideShow = \"style=\\\"display:none\\\"\";\n"
$vOut.="  vContent += \"<OUTTEXT class='\"+vName+\"' id='\"+vName+\"-CON-NA' \"+vHideShow+\">\"+AP+ \"???\" + AP +\"</OUTTEXT>\";\n"
$vOut.="  i = 0;\n"
$vOut.="  while (lower(i,vConnectionArray.length)) {\n"
$vOut.="    vContent += \"<OUTTEXT class='\"+vName+\"' id='\"+vName+\"-CON-\"+i+\"'  \"+vHideShow+\">\"+AP+vConnectionArray[i] + AP +\"</OUTTEXT>\";\n"
$vOut.="  i++;\n"
$vOut.="  }\n"
$vOut.="  vContent += vSpace+\"</td><td valign='center' align='left'>\";\n"
$vOut.="  i = 0;\n"
$vOut.="  for (var vID in pAllSteps) {\n"
$vOut.="  i++;\n"
$vOut.="    if (i == pStep) {\n"
$vOut.="      vHideShow = \"style=\\\"display:block\\\"\";\n"
$vOut.="    } else {\n"
$vOut.="      vHideShow = \"style=\\\"display:none\\\"\";\n"
$vOut.="    }\n"
$vOut.="    vContent += \"<OUTTEXT class='\"+vName+\"' id='\"+vName+\"-STEP-\"+vID+\"' stepid='\"+vID+\"' \"+vHideShow+\">\"+getStepDef4ID(vID) +\"</OUTTEXT>\";\n"
$vOut.="  };\n"
$vOut.="  vContent += \"</td></tr></table>\"\n"
$vOut.="  return vContent;\n"
$vOut.="}\n"
$vOut.="function getJustificationHTML(pJustList,pAllSteps,pStep,pCount) {\n"
$vOut.="  var vContent = \"\";\n"
$vOut.="  var vName = \"outJUSTIFICATION\"+vQID; \n"
$vOut.="  var vID = \"\";\n"
$vOut.="  vContent += \"<u>\"+ vLanguage[\"Justifications\"]+\":</u> [<IDTAG class='VIEWID\"+vQID+pStep+\"' id='dVIEW\"+vQID+pStep+\"'>??ID??</IDTAG>]\";\n"
$vOut.="  vContent +=\"<ul>\";\n"
$vOut.="  var k=0;\n"
$vOut.="  var vStepDef = \"\";\n"
$vOut.="  while (lower(k,pJustList.length)) {\n"
$vOut.="    vID = pJustList[k].id;\n"
$vOut.="    vContent += \"<li class='\"+vName+pStep+\"' id='\"+vName+pStep+\"-\"+vID+\"' stepid='\"+vID+\"'>\"+ getStepDef4ID(vID) +\"</li>\";\n"
$vOut.="    k++;\n"
$vOut.="  }\n"
$vOut.="  for (var vID in pAllSteps) {\n"
$vOut.="      vContent += \"<li class='\"+vName+pStep+\"' id='\"+vName+pStep+\"-\"+vID+\"' stepid='\"+vID+\"'>\"+getStepDef4ID(vID) +\"</li>\";\n"
$vOut.="  };\n"
$vOut.="  vContent += \"</ul>\";\n"
$vOut.="  return vContent;\n"
$vOut.="}\n"
$vOut.="function getJustificationCheckboxHTML(pJustList,pAllSteps,pStep,pCount) {\n"
$vOut.="  var vContent = \"\";\n"
$vOut.="  var vName = \"sJUSTIFICATION\"+vQID+pStep;\n"
$vOut.="  var vID = \"\";\n"
$vOut.="  var vStepDef = \"\";\n"
$vOut.="  vContent += \"<b>\"+vLanguage[\"Justifications\"]+\": [</b><b class='VIEWID\"+vQID+pStep+\"' id='cVIEW\"+vQID+pStep+\"'>??ID??</b><b>]</b>\";\n"
$vOut.="  vContent += \"<input type='button'  value='  OK  ' step='\"+pStep+\"' name='bOK\"+vQID+pStep+\"' onclick=\\\"toggleJustification(\"+pStep+\")\\\" ><br/>\";\n"
$vOut.="  var k=0;\n"
$vOut.="    while (lower(k,pJustList.length)) {\n"
$vOut.="      vID = pJustList[k].id;\n"
$vOut.="    vContent += getCheckbox4Step(pStep, vName ,vID ,getStepDef4ID(vID) )\n"
$vOut.="      k++;\n"
$vOut.="    }\n"
$vOut.="  for (var vID in pAllSteps)  {\n"
$vOut.="    vContent += getCheckbox4Step(pStep, vName ,vID ,getStepDef4ID(vID) )\n"
$vOut.="  };\n"
$vOut.="  return vContent;\n"
$vOut.="}\n"
$vOut.="function getCheckbox4Step(pStep,pName,pID,pStepDef) {\n"
$vOut.="  var vContent = \"<DIV class='checkboxJUSTIFICATION\"+vQID+\"' id='checkboxJUSTIFICATION\"+vQID+pStep+\"-\"+pID+\"'>\";\n"
$vOut.="  vContent += \"<input type='checkbox' class='\"+pName+\"' name='\"+pName+\"-\"+pID+\"' step='\"+pStep+\"' id='\"+pName+\"-\"+pID+\"' value='\"+pID+\"' onchange=\\\"updateJustifications(\"+pStep+\")\\\" /> \";\n"
$vOut.="    vContent += pStepDef +\"</DIV>\";\n"
$vOut.="    return vContent;\n"
$vOut.="}\n"
$vOut.="function greater(a,b) {\n"
$vOut.="  eval(decodeURI(\"var vReturn%20=%20(a%3Eb);\"));\n"
$vOut.="  return vReturn;\n"
$vOut.="}\n"
$vOut.="function lower(a,b) {\n"
$vOut.="  eval(decodeURI(\"vReturn%20=%20(a%3Cb);\"));\n"
$vOut.="  return vReturn;\n"
$vOut.="}\n"
$vOut.="function toggleHide(pObjectID) {\n"
$vOut.="  var vNode = document.getElementById(pObjectID);\n"
$vOut.="  if (!vNode) {\n"
$vOut.="    alertDOM(\"DOM Node with ID='\"+pObjectID+\"' undefined! e-Proof Emulator.html:170\")\n"
$vOut.="  } else {\n"
$vOut.="    if (vNode.style.display==\"none\") {\n"
$vOut.="      vNode.style.visibility = \"visible\";\n"
$vOut.="      vNode.style.display = \"block\";\n"
$vOut.="    } else {\n"
$vOut.="      vNode.style.visibility = \"hidden\";\n"
$vOut.="      vNode.style.display = \"none\";\n"
$vOut.="    }\n"
$vOut.="  }  \n"
$vOut.="}\n"
$vOut.="function toggleElementHide(pObjectID) {\n"
$vOut.="  var vNode = document.getElementById(pObjectID);\n"
$vOut.="  if (!vNode) {\n"
$vOut.="    alertDOM(\"DOM Node with ID='\"+pObjectID+\"' undefined! e-Proof Emulator.html:170\")\n"
$vOut.="  } else {\n"
$vOut.="    if (vNode.style.visibility==\"hidden\") {\n"
$vOut.="      vNode.style.visibility = \"visible\";\n"
$vOut.="    } else {\n"
$vOut.="      vNode.style.visibility = \"hidden\";\n"
$vOut.="    }\n"
$vOut.="  }  \n"
$vOut.="}\n"
$vOut.="function hideElement(pObjectID) {\n"
$vOut.="  var vNode = document.getElementById(pObjectID);\n"
$vOut.="  if (!vNode) {\n"
$vOut.="    alertDOM(\"DOM Node with ID='\"+pObjectID+\"' undefined! e-Proof Emulator.html:170\")\n"
$vOut.="  } else {\n"
$vOut.="    vNode.style.visibility = \"hidden\";\n"
$vOut.="  }   \n"
$vOut.="}\n"
$vOut.="function showElement(pObjectID) {\n"
$vOut.="  var vNode = document.getElementById(pObjectID);\n"
$vOut.="  if (!vNode) {\n"
$vOut.="    alertDOM(\"DOM Node with ID='\"+pObjectID+\"' undefined! e-Proof Emulator.html:170\")\n"
$vOut.="  } else {\n"
$vOut.="    vNode.style.visibility =\"visible\";\n"
$vOut.="  }   \n"
$vOut.="}\n"
$vOut.="function hideObject(pObjectID) {\n"
$vOut.="  var vNode = document.getElementById(pObjectID);\n"
$vOut.="  if (!vNode) {\n"
$vOut.="    alertDOM(\"DOM Node with ID='\"+pObjectID+\"' undefined! e-Proof Emulator.html:170\")\n"
$vOut.="  } else {\n"
$vOut.="    vNode.style.display = \"none\";\n"
$vOut.="    vNode.style.visibility = \"hidden\";\n"
$vOut.="  } \n"
$vOut.="}\n"
$vOut.="function showObject(pObjectID) {\n"
$vOut.="  var vNode = document.getElementById(pObjectID);\n"
$vOut.="  if (!vNode) {\n"
$vOut.="    alertDOM(\"DOM Node with ID='\"+pObjectID+\"' undefined! e-Proof Emulator.html:170\")\n"
$vOut.="  } else {\n"
$vOut.="    vNode.style.display = \"block\";\n"
$vOut.="    vNode.style.visibility =\"visible\"\n"
$vOut.="  }\n"
$vOut.="}\n"
$vOut.="function hideEditLines(pCount) {\n"
$vOut.="  var vListArray = document.getElementsByClassName(\"editSTUDENTANSWER\"+vQID);\n"
$vOut.="  var vNr = 0;\n"
$vOut.="  while (lower(vNr,pCount)) {\n"
$vOut.="    vNr++;\n"
$vOut.="    hideObject(\"editSTUDENTANSWER\"+vQID+vNr);\n"
$vOut.="  }\n"
$vOut.="}\n"
$vOut.="function showEditLines(pCount) {\n"
$vOut.="  var vNr = 0;\n"
$vOut.="  while (lower(vNr,pCount)) {\n"
$vOut.="    vNr++;\n"
$vOut.="    showObject(\"editSTUDENTANSWER\"+vQID+vNr);\n"
$vOut.="  }\n"
$vOut.="}\n"
$vOut.="function setVisibility4Proof(pSelected,pForm) {\n"
$vOut.="  var vNode = createNodeQN(\"Display Selector\",\"qn\"+ThisQ+\"001\");\n"
$vOut.="  vNode.value = pSelected;\n"
$vOut.="  if (pSelected==\"Assessment\") {\n"
$vOut.="    updateInput2IMathAS(pForm);\n"
$vOut.="  };\n"
$vOut.="  setDisplayOptions();\n"
$vOut.="}\n"
$vOut.="function setDisplayOptions() {\n"
$vOut.="  var vNode = createNodeQN(\"Display Selector\",\"qn\"+ThisQ+\"001\");\n"
$vOut.="  vSelected = vNode.value;\n"
$vOut.="  var vListArray = document.getElementsByClassName(\"cVIEWJUSTIFICATION\"+vQID);\n"
$vOut.="  if (vSelected==\"Short\") {\n"
$vOut.="    showObject(\"EDITPROOF\"+vQID);\n"
$vOut.="    showObject(\"STUDENTANSWERLIST\"+vQID);\n"
$vOut.="    showEditLines(vListArray.length);\n"
$vOut.="    hideObject(\"ASSESSMENT\"+vQID);\n"
$vOut.="    hideObject(\"SOLUTION\"+vQID);\n"
$vOut.="    setShortJustification(vListArray,true);\n"
$vOut.="  } else   if (vSelected==\"Complete\") {\n"
$vOut.="    showObject(\"EDITPROOF\"+vQID);\n"
$vOut.="    showObject(\"STUDENTANSWERLIST\"+vQID);\n"
$vOut.="    showEditLines(vListArray.length);\n"
$vOut.="    hideObject(\"ASSESSMENT\"+vQID);\n"
$vOut.="    hideObject(\"SOLUTION\"+vQID);\n"
$vOut.="    setShortJustification(vListArray,false);\n"
$vOut.="  } else   if (vSelected==\"Hide\") {\n"
$vOut.="    showObject(\"EDITPROOF\"+vQID);\n"
$vOut.="    showObject(\"STUDENTANSWERLIST\"+vQID);\n"
$vOut.="    hideEditLines(vListArray.length);\n"
$vOut.="    hideObject(\"ASSESSMENT\"+vQID);\n"
$vOut.="    hideObject(\"SOLUTION\"+vQID);\n"
$vOut.="  } else   if (vSelected==\"Assessment\") {\n"
$vOut.="    showObject(\"ASSESSMENT\"+vQID);\n"
$vOut.="    hideObject(\"EDITPROOF\"+vQID);\n"
$vOut.="    hideObject(\"STUDENTANSWERLIST\"+vQID);\n"
$vOut.="    hideObject(\"SOLUTION\"+vQID);\n"
$vOut.="  } else   if (vSelected==\"Solution\") {\n"
$vOut.="    showObject(\"SOLUTION\"+vQID);\n"
$vOut.="    hideObject(\"EDITPROOF\"+vQID);\n"
$vOut.="    hideObject(\"ASSESSMENT\"+vQID);\n"
$vOut.="    hideObject(\"STUDENTANSWERLIST\"+vQID);\n"
$vOut.="    }\n"
$vOut.="}\n"
$vOut.="function setShortJustification(pListArray,pBoolean) {\n"
$vOut.="  var i=0;\n"
$vOut.="  while (lower(i,pListArray.length)) {\n"
$vOut.="    pListArray[i].checked = !(pBoolean);\n"
$vOut.="    i++;\n"
$vOut.="  };\n"
$vOut.="  i = 0;\n"
$vOut.="  while (lower(i,pListArray.length)) {\n"
$vOut.="    i++;\n"
$vOut.="    changeViewJustification(i);\n"
$vOut.="  }\n"
$vOut.="  if (pBoolean) {\n"
$vOut.="    i = 0;\n"
$vOut.="    while (lower(i,pListArray.length)) {\n"
$vOut.="      i++;\n"
$vOut.="      hideElement(\"bJUSTIFICATION\"+vQID+i);\n"
$vOut.="      hideElement(\"inJUSTIFICATION\"+vQID+i);\n"
$vOut.="    }\n"
$vOut.="  } else {\n"
$vOut.="    i = 0;\n"
$vOut.="    while (lower(i,pListArray.length)) {\n"
$vOut.="      i++;\n"
$vOut.="      showElement(\"bJUSTIFICATION\"+vQID+i);\n"
$vOut.="      showElement(\"inJUSTIFICATION\"+vQID+i);\n"
$vOut.="    }\n"
$vOut.="  }\n"
$vOut.="}\n"
$vOut.="function setVisibility4Unused() {\n"
$vOut.="  var vListNode = document.getElementsByClassName(\"STUDENTANSWER\"+vQID);\n"
$vOut.="  var k=0;\n"
$vOut.="  while (lower(k,vListNode.length)) {\n"
$vOut.="    setVisibility4Step(vListNode[k]);\n"
$vOut.="    k++;\n"
$vOut.="  }\n"
$vOut.="}\n"
$vOut.="function setVisibility4Step(pNode) {\n"
$vOut.="    var vStep = getStep4NodeID(pNode.id);\n"
$vOut.="  if (pNode.parentNode.id == \"UNUSEDSTEPS\"+vQID) {\n"
$vOut.="    hideElement(\"bDelete\"+vQID+vStep);\n"
$vOut.="    hideElement(\"bJUSTIFICATION\"+vQID+vStep);\n"
$vOut.="    hideElement(\"inJUSTIFICATION\"+vQID+vStep);\n"
$vOut.="    hideElement(\"sCONNECTION\"+vQID+vStep);\n"
$vOut.="    hideElement(\"sSTEP\"+vQID+vStep);\n"
$vOut.="    showElement(\"bUseStep\"+vQID+vStep);\n"
$vOut.="  } else {\n"
$vOut.="    showElement(\"bDelete\"+vQID+vStep);\n"
$vOut.="    showElement(\"bJUSTIFICATION\"+vQID+vStep);\n"
$vOut.="    showElement(\"inJUSTIFICATION\"+vQID+vStep);\n"
$vOut.="    showElement(\"sCONNECTION\"+vQID+vStep);\n"
$vOut.="    showElement(\"sSTEP\"+vQID+vStep);\n"
$vOut.="    hideElement(\"bUseStep\"+vQID+vStep);\n"
$vOut.="  };\n"
$vOut.="  setDisplayOptions();\n"
$vOut.="  var vUnused4Proof = document.getElementById(\"UNUSEDSTEPS\"+vQID);\n"
$vOut.="  var vUnusedList = vUnused4Proof.getElementsByClassName(\"STUDENTANSWER\"+vQID);\n"
$vOut.="  var vCountUnused = vUnusedList.length;\n"
$vOut.="  if (greater(vCountUnused,0)) {\n"
$vOut.="    showElement(\"bToggleUnused\"+vQID); //\"+vQID+\"\n"
$vOut.="  } else {\n"
$vOut.="    hideElement(\"bToggleUnused\"+vQID);\n"
$vOut.="  }\n"
$vOut.="}\n"
$vOut.="function getHideStepIDs() {\n"
$vOut.="  var vAllSteps = new Array();\n"
$vOut.="  var vListArray = new Array();\n"
$vOut.="  var vList = null;\n"
$vOut.="  vListArray.push(document.getElementsByClassName(\"PROOFSTEP\"+vQID));\n"
$vOut.="  vListArray.push(document.getElementsByClassName(\"CONCLUSION\"+vQID));\n"
$vOut.="  var k=0;\n"
$vOut.="  var j=0;\n"
$vOut.="  while (lower(k,vListArray.length)) {\n"
$vOut.="    vList = vListArray[k];\n"
$vOut.="    j=0;\n"
$vOut.="    while (lower(j,vList.length)) if (vList[j].id) {\n"
$vOut.="      vID = vList[j].id;\n"
$vOut.="      vStepDef = vList[j].childNodes[0].nodeValue;\n"
$vOut.="      vAllSteps[vID] = vStepDef;\n"
$vOut.="      j++\n"
$vOut.="    };\n"
$vOut.="    k++;\n"
$vOut.="  };\n"
$vOut.="  return vAllSteps;\n"
$vOut.="}\n"
$vOut.="function getAllStepIDs() {\n"
$vOut.="  var vAllSteps = new Array();\n"
$vOut.="  var vListArray = new Array();\n"
$vOut.="  var vList = null;\n"
$vOut.="  vListArray.push(document.getElementsByClassName(\"PRECONDITION\"+vQID));\n"
$vOut.="  vListArray.push(document.getElementsByClassName(\"PROOFSTEP\"+vQID));\n"
$vOut.="  vListArray.push(document.getElementsByClassName(\"CONCLUSION\"+vQID));\n"
$vOut.="  var k=0;\n"
$vOut.="  var j=0;\n"
$vOut.="  while (lower(k,vListArray.length)) {\n"
$vOut.="    vList = vListArray[k];\n"
$vOut.="    j=0;\n"
$vOut.="    while (lower(j,vList.length)) if (vList[j].id) {\n"
$vOut.="      vID = vList[j].id;\n"
$vOut.="      vStepDef = vList[j].childNodes[0].nodeValue;\n"
$vOut.="      vAllSteps[vID] = vStepDef;\n"
$vOut.="      j++;\n"
$vOut.="    };\n"
$vOut.="    k++\n"
$vOut.="  };\n"
$vOut.="  return vAllSteps;\n"
$vOut.="}\n"
$vOut.="function appendStep(pStep,pCount) {\n"
$vOut.="  var vStudentAnswer = document.getElementById(\"STUDENTANSWER\"+vQID+pStep);\n"
$vOut.="  var vUnused4Proof  = document.getElementById(\"UNUSEDSTEPS\"+vQID);\n"
$vOut.="  moveStepOrder(pStep,0,pCount);\n"
$vOut.="  setVisibility4Step(vStudentAnswer);\n"
$vOut.="}\n"
$vOut.="function deleteProofStep(pStep,pCount) {\n"
$vOut.="  var vNode4ID = document.getElementById(\"sSTEP\"+vQID+pStep);\n"
$vOut.="  Check = confirm(vLanguage[\"Delete_Prompt\"] + CR + vLanguage[\"ProofStep\"]+\" [\"+vNode4ID.value+\"] \");\n"
$vOut.="  if (Check) {\n"
$vOut.="    moveStepOrder(pStep,pCount+1,pCount);\n"
$vOut.="  } else {\n"
$vOut.="    alert(\"CANCEL: \"+ vLanguage[\"ProofStep\"]+\" [\"+vNode4ID.value+\"] \"+vLanguage[\"Deleted\"]);\n"
$vOut.="  }\n"
$vOut.="}\n"
$vOut.="function positionChange(pStep,pNewPos,pCount) {\n"
$vOut.="  var vListNode     = document.getElementsByClassName(\"STUDENTANSWER\"+vQID);\n"
$vOut.="  var vOldPos = getList_Position(vListNode,\"STUDENTANSWER\"+vQID,pStep);\n"
$vOut.="  moveStep(vOldPos,pNewPos);  \n"
$vOut.="}\n"
$vOut.="function moveStepOrder(pStep,pNewPos,pCount) {\n"
$vOut.="  var vListNode     = document.getElementsByClassName(\"STUDENTANSWER\"+vQID);\n"
$vOut.="  var vOldPos = getList_Position(vListNode,\"STUDENTANSWER\"+vQID,pStep);\n"
$vOut.="  moveStep(vOldPos,pNewPos);\n"
$vOut.="}\n"
$vOut.="function moveStepID(pStep,pID,pCount) {\n"
$vOut.="  var vStudentAnswerList     = document.getElementsByClassName(\"STUDENTANSWER\"+vQID);\n"
$vOut.="  var vNewPos = getList_Position(vStudentAnswerList,\"STUDENTANSWER\"+vQID,pStep);\n"
$vOut.="  var vOldPos = getStepIndex4ID(pID); \n"
$vOut.="  moveStep(vOldPos,vNewPos);\n"
$vOut.="  updateStepChange(pStep);\n"
$vOut.="}\n"
$vOut.="function moveStep(pOldPos,pNewPos) {\n"
$vOut.="  var vListNode     = document.getElementsByClassName(\"STUDENTANSWER\"+vQID);\n"
$vOut.="  var vOldPos      =  pOldPos; \n"
$vOut.="  var vNewPos      =  pNewPos; \n"
$vOut.="  var vProof        = document.getElementById(\"STUDENTANSWERLIST\"+vQID)\n"
$vOut.="  var vUnused4Proof = document.getElementById(\"UNUSEDSTEPS\"+vQID);\n"
$vOut.="  var vUnused4Nodes = vUnused4Proof.getElementsByClassName(\"STUDENTANSWER\"+vQID);\n"
$vOut.="  var vCount        = vListNode.length;\n"
$vOut.="  var vCountUnused  = vUnused4Nodes.length;\n"
$vOut.="    var vCountProof   = vListNode.length - vCountUnused;\n"
$vOut.="    if (pNewPos == -1) {\n"
$vOut.="      alert(\"No Move-Operation with pNewPos=\"+vNewPos+\"=-1\");\n"
$vOut.="    } else if (vOldPos == vNewPos) {\n"
$vOut.="    } else {\n"
$vOut.="      var vOldNode = vListNode[vOldPos-1]; //document.getElementById(\"STUDENTANSWER\"+pStep);\n"
$vOut.="     var vOldParentNode = vOldNode.parentNode;\n"
$vOut.="    var vRemovedChild = vOldParentNode.removeChild(vOldNode);\n"
$vOut.="    if (pNewPos == 0) {\n"
$vOut.="        vProof.appendChild(vRemovedChild);\n"
$vOut.="        vCountProof++;\n"
$vOut.="        pNewPos = vCountProof;\n"
$vOut.="      } else if (lower(pNewPos , vCount - vCountUnused)) {\n"
$vOut.="        vProof.insertBefore(vRemovedChild,vListNode[vNewPos-1]);\n"
$vOut.="      } else if (pNewPos == (vCount - vCountUnused)) {\n"
$vOut.="        vProof.appendChild(vRemovedChild);\n"
$vOut.="      } else {\n"
$vOut.="        vUnused4Proof.appendChild(vRemovedChild);\n"
$vOut.="      };\n"
$vOut.="      vCountProof   = vListNode.length - vUnused4Proof.childNodes.length;\n"
$vOut.="    append_PreviousStep_Justification();\n"
$vOut.="    setVisibility4Step(vRemovedChild);\n"
$vOut.="    updateInput();\n"
$vOut.="  }\n"
$vOut.="}\n"
$vOut.="function setJustification(pObjectID,pNr,pID) {\n"
$vOut.="    var vObject = document.getElementById(pObjectID);\n"
$vOut.="    if (vObject) {\n"
$vOut.="      if (vObject.value == \"\") {\n"
$vOut.="          vObject.value = pID\n"
$vOut.="      } else {\n"
$vOut.="        var vString = \"#,\"+vObject.value+\",\";\n"
$vOut.="        if (greater(0,vString.indexOf(\",\"+pID+\",\")) ) {\n"
$vOut.="            vObject.value += \",\"+pID;\n"
$vOut.="          }\n"
$vOut.="      }\n"
$vOut.="      alert(\"Begruendung - Beweisfragment \"+pNr+\": [\"+vObject.value+\"]\");\n"
$vOut.="    } else {\n"
$vOut.="      alertDOM(\"DOM Object \"+pObjectID+\" does not exist\"); \n"
$vOut.="    }\n"
$vOut.="}\n"
$vOut.="function changeEditJustification(pStep) {\n"
$vOut.="  setJustificationCheckbox(pStep);\n"
$vOut.="  changeViewJustification(pStep);\n"
$vOut.="}\n"
$vOut.="function changeViewJustification(pStep) {\n"
$vOut.="  var vCheckViewBox = document.getElementById(\"cVIEWJUSTIFICATION\"+vQID+pStep);  \n"
$vOut.="  var vCheckEditBox = document.getElementById(\"cEDITJUSTIFICATION\"+vQID+pStep);  \n"
$vOut.="  var vInJustifications = document.getElementById(\"inJUSTIFICATION\"+vQID+pStep).value;  \n"
$vOut.="  hideAllJustifications(pStep);\n"
$vOut.="  if (vCheckEditBox.checked) {\n"
$vOut.="    hideObject(\"dVIEWJUSTIFICATION\"+vQID+pStep);\n"
$vOut.="    showObject(\"dEDITJUSTIFICATION\"+vQID+pStep);\n"
$vOut.="  } else if (vCheckViewBox.checked) {\n"
$vOut.="    if (vInJustifications != '') {\n"
$vOut.="      showObject(\"dVIEWJUSTIFICATION\"+vQID+pStep);\n"
$vOut.="    } else {\n"
$vOut.="      hideObject(\"dVIEWJUSTIFICATION\"+vQID+pStep);\n"
$vOut.="    }\n"
$vOut.="    hideObject(\"dEDITJUSTIFICATION\"+vQID+pStep);\n"
$vOut.="  } else {\n"
$vOut.="    hideObject(\"dVIEWJUSTIFICATION\"+vQID+pStep);\n"
$vOut.="    hideObject(\"dEDITJUSTIFICATION\"+vQID+pStep);\n"
$vOut.="  };\n"
$vOut.="  updateTextIDs(pStep);\n"
$vOut.="  append_PreviousStep_Justification();\n"
$vOut.="  showSelectedJustifications(pStep);  \n"
$vOut.="}\n"
$vOut.="function append_PreviousStep_Justification() {\n"
$vOut.="  var vListID = document.getElementsByClassName(\"sSTEP\"+vQID);\n"
$vOut.="  var vListNode = document.getElementsByClassName(\"STUDENTANSWER\"+vQID);\n"
$vOut.="  var vVisibleJustArray = new Array();\n"
$vOut.="  var vStepArray = new Array();\n"
$vOut.="  var vStep = 0;\n"
$vOut.="  var vName = \"\";\n"
$vOut.="  var vCheckName = \"\";\n"
$vOut.="  var i=0;\n"
$vOut.="  var k=0;\n"
$vOut.="  while (lower(i,vListNode.length))  {\n"
$vOut.="    if (vListNode[i].id) {\n"
$vOut.="      vStep = getStep4NodeID(vListNode[i].id);\n"
$vOut.="      vName = \"checkboxJUSTIFICATION\"+vQID+vStep;\n"
$vOut.="      k=0;\n"
$vOut.="      while (lower(k,vVisibleJustArray.length)) { \n"
$vOut.="        vCheckName = vName+\"-\"+vVisibleJustArray[k]; \n"
$vOut.="        showObject(vCheckName);\n"
$vOut.="        k++;\n"
$vOut.="      };\n"
$vOut.="      vStepArray.push(vListNode[i].step);\n"
$vOut.="      vVisibleJustArray.push(vListID[i].value);\n"
$vOut.="    };\n"
$vOut.="    i++;\n"
$vOut.="  }\n"
$vOut.="}\n"
$vOut.="function hideAllJustifications(pStep) {\n"
$vOut.="  if (pStep) {\n"
$vOut.="    var vOutName    = \"outJUSTIFICATION\"+vQID+pStep;\n"
$vOut.="    var vSelectName = \"sJUSTIFICATION\"+vQID+pStep;\n"
$vOut.="    var vCheckName  = \"checkboxJUSTIFICATION\"+vQID+pStep;\n"
$vOut.="    var vViewList = document.getElementsByClassName(vOutName);\n"
$vOut.="    var k=0;\n"
$vOut.="  while (lower(k,vViewList.length)) if (vViewList[k].style) {\n"
$vOut.="      vViewList[k].style.display = \"none\";\n"
$vOut.="      k++;\n"
$vOut.="    };\n"
$vOut.="    var vHideSteps = getHideStepIDs();\n"
$vOut.="    var vCheckboxes = document.getElementsByClassName(vSelectName);\n"
$vOut.="    for (var vID in vHideSteps) if (pStep) {\n"
$vOut.="      hideObject(vCheckName +\"-\"+vID);\n"
$vOut.="    }; \n"
$vOut.="  }\n"
$vOut.="}\n"
$vOut.="function hideAllSteps(pStep) {\n"
$vOut.="  var vAllSteps = getAllStepIDs();\n"
$vOut.="  if (pStep) {\n"
$vOut.="    var vOutName = \"outSTEPDISPLAY\"+vQID+pStep;\n"
$vOut.="    var vViewList = document.getElementsByClassName(vOutName);\n"
$vOut.="    var k=0;\n"
$vOut.="  while (lower(k,vViewList.length)) if (vViewList[k].style) {\n"
$vOut.="      vViewList[k].style.display = \"none\";\n"
$vOut.="      k++;\n"
$vOut.="    };\n"
$vOut.="  }\n"
$vOut.="}\n"
$vOut.="function toggleEdit(pStep) {\n"
$vOut.="  var vListIDs      = document.getElementsByClassName(\"inSTEPID\"+vQID);\n"
$vOut.="  var vStepDefNode  = document.getElementById(\"inSTEPDEF\"+vQID+pStep);\n"
$vOut.="  var vTextareaNode = document.getElementById(vEditorID + vQID + pStep);\n"
$vOut.="  vTextareaNode.value = vStepDefNode.value.replace(/__n__/g,CR);\n"
$vOut.="  toggleHide(\"STEPEDITOR\"+vQID+pStep);\n"
$vOut.="  hideObject(\"inSTEPDEF\"+vQID+pStep);\n"
$vOut.="}\n"
$vOut.="function toggleJustification(pStep) {\n"
$vOut.="  if (!pStep) {\n"
$vOut.="    alert(\"pStep is not defined in toggleJustification\");\n"
$vOut.="  } else if (pStep > 0) {\n"
$vOut.="    var vCheckViewBox = document.getElementById(\"cVIEWJUSTIFICATION\"+vQID+pStep);  \n"
$vOut.="    var vCheckEditBox = document.getElementById(\"cEDITJUSTIFICATION\"+vQID+pStep);  \n"
$vOut.="    var vID = document.getElementById(\"inSTEPID\"+vQID+pStep).value;  \n"
$vOut.="    vCheckEditBox.checked = !vCheckEditBox.checked;\n"
$vOut.="    hideAllJustifications(pStep);\n"
$vOut.="    append_PreviousStep_Justification();\n"
$vOut.="    showSelectedJustifications(pStep);\n"
$vOut.="    changeViewJustification(pStep);\n"
$vOut.="  } else {\n"
$vOut.="    alert(\"Toggle New Step\");\n"
$vOut.="  }\n"
$vOut.="}\n"
$vOut.="function showSelectedJustifications(pStep) {\n"
$vOut.="  var vInputNode = document.getElementById(\"inJUSTIFICATION\"+vQID+pStep);\n"
$vOut.="  var vJustString = vInputNode.value.replace(/\s/g,\"\");\n"
$vOut.="  if (vJustString != \"\") {\n"
$vOut.="    var vID_Array = vJustString.split(\",\");\n"
$vOut.="    var vNode = null;\n"
$vOut.="    var vOutNodeID = \"\"\n"
$vOut.="    var k=0;\n"
$vOut.="    while (lower(k,vID_Array.length)) {\n"
$vOut.="      vOutNodeID = \"outJUSTIFICATION\"+vQID+pStep+\"-\"+vID_Array[k];\n"
$vOut.="      vNode = document.getElementById(vOutNodeID);\n"
$vOut.="      if(vNode) {\n"
$vOut.="        showObject(vOutNodeID);\n"
$vOut.="      } else {\n"
$vOut.="        alertDOM(\"Error (Node=\"+vOutNodeID+\"): Justification with the ID='\"+vID_Array[k]+\"' does not exist!\");\n"
$vOut.="      };\n"
$vOut.="      k++;\n"
$vOut.="    }\n"
$vOut.="  }\n"
$vOut.="}\n"
$vOut.="function setJustificationCheckbox(pStep) {\n"
$vOut.="  var vInJustification\n"
$vOut.="  var vCheckboxes = document.getElementsByClassName(\"sJUSTIFICATION\"+vQID+pStep);\n"
$vOut.="  var vInputNode = document.getElementById(\"inJUSTIFICATION\"+vQID+pStep);\n"
$vOut.="  var vJustString = vInputNode.value.replace(/\s/g,\"\");\n"
$vOut.="  var vID_Array = vJustString.split(\",\");\n"
$vOut.="  var k=0;\n"
$vOut.="  var i=0;\n"
$vOut.="  while (lower(k,vID_Array.length)) {\n"
$vOut.="    i=0;\n"
$vOut.="    while (lower(i,vCheckboxes.length)) {\n"
$vOut.="      if (vID_Array[k] == vCheckboxes[i].value) {\n"
$vOut.="        vCheckboxes[i].checked = true;\n"
$vOut.="      };\n"
$vOut.="      i++;\n"
$vOut.="    };\n"
$vOut.="    k++;\n"
$vOut.="  };\n"
$vOut.="  showSelectedJustifications(pStep);\n"
$vOut.="}\n"
$vOut.="function getStepDef4ID(pID) {\n"
$vOut.="  var vNode = document.getElementById(pID);\n"
$vOut.="  if (vNode.id) {\n"
$vOut.="    return  \" [\"+vNode.id+\"] \" + vSpace + decodeValue(vNode.childNodes[0].nodeValue);\n"
$vOut.="  } else {\n"
$vOut.="    return \" [pID] ???\";\n"
$vOut.="  }\n"
$vOut.="}\n"
$vOut.="function getStepDef(pNode) {\n"
$vOut.="  if (pNode.id) {\n"
$vOut.="    return \" [\"+pNode.id+\"] \" + vSpace + decodeValue(pNode.childNodes[0].nodeValue);\n"
$vOut.="  } else {\n"
$vOut.="    return \" [???] getStepDef(pNode??)\";\n"
$vOut.="  }\n"
$vOut.="}\n"
$vOut.="function saveASCIImath(pNodeName,pString) {\n"
$vOut.="  var vOutNode = removeChildContent(pNodeName);\n"
$vOut.="  vOutNode.innerHTML = decodeTextarea(pString);\n"
$vOut.="  AMprocessNode(vOutNode);\n"
$vOut.="}\n"
$vOut.="function removeChildContent(pNodeID) {\n"
$vOut.="  var vOutNode = document.getElementById(pNodeID);\n"
$vOut.="  if (!vOutNode) {\n"
$vOut.="    alert(\"No vOutNode for DOM-Node with ID='\"+pNodeID+\"'\");\n"
$vOut.="  } else {\n"
$vOut.="    var i=0;\n"
$vOut.="    var n=vOutNode.childNodes.length;\n"
$vOut.="    while (lower(i,n)) {\n"
$vOut.="      vOutNode.removeChild(vOutNode.firstChild);\n"
$vOut.="      i++;\n"
$vOut.="    };\n"
$vOut.="  };\n"
$vOut.="  return vOutNode;\n"
$vOut.="}\n"
$vOut.="function getList_Position(pList,pName,pStep) { \n"
$vOut.="  var vReturn = pList.length+1;\n"
$vOut.="  var i=0;\n"
$vOut.="  while (lower(i,pList.length)) {\n"
$vOut.="    if   (pList[i].id == pName+pStep) {\n"
$vOut.="      vReturn = i+1;\n"
$vOut.="    };\n"
$vOut.="    i++;\n"
$vOut.="  };\n"
$vOut.="  return vReturn;\n"
$vOut.="}\n"
$vOut.="function getStepCountSelectorHTML()  {\n"
$vOut.="  var vAllSteps = getAllStepIDs();\n"
$vOut.="  var vContent = \"\";\n"
$vOut.="  var vContent = \"<SELECT class='sSTEPCOUNT\"+vQID+\"'  id='sSTEPCOUNT\"+vQID+\"' onchange=\\\"updateStepCount(this.value)\\\">\";\n"
$vOut.="  var vNr=0;\n"
$vOut.="  var vMax=0;\n"
$vOut.="  for (var iID in vAllSteps) {\n"
$vOut.="    vNr++;\n"
$vOut.="  };\n"
$vOut.="  vMax = vNr;\n"
$vOut.="  vNr=1;\n"
$vOut.="  while (lower(vNr,vMax+1)) {\n"
$vOut.="    if (vNr == vMax) {\n"
$vOut.="      vContent +=\"<option class='COUNT\"+iID+\"' value='\"+vNr+\"' selected>\"+vNr+\"</option>\";\n"
$vOut.="      } else {\n"
$vOut.="        vContent +=\"<option class='COUNT\"+iID+\"' value='\"+vNr+\"'>\"+vNr+\"</option>\";\n"
$vOut.="      }\n"
$vOut.="    vNr++;\n"
$vOut.="    }\n"
$vOut.="  vContent +=\"</SELECT>\";\n"
$vOut.="  return vContent;\n"
$vOut.="}\n"
$vOut.="function getListIMathAS(pTextareaID) {\n"
$vOut.="  var vInput = document.getElementById(\"imath\"+pTextareaID).value;\n"
$vOut.="  var vListArray = vInput.split(CR);\n"
$vOut.="  var vContent = \"\";\n"
$vOut.="  if (vInput) {\n"
$vOut.="    vContent += \"<ul>\";\n"
$vOut.="    vContent += getItemsIMathAS(vListArray);\n"
$vOut.="    vContent +=\"</ul>\";\n"
$vOut.="  } else {\n"
$vOut.="    alert(\"Textarea: 'imath\"+pTextareaID+\"' was undefined!\");\n"
$vOut.="  }\n"
$vOut.="  return vContent;\n"
$vOut.="}\n"
$vOut.="function getItemsIMathAS(pListArray) {\n"
$vOut.="  var vContent = \"\";\n"
$vOut.="  if (pListArray) {\n"
$vOut.="    var k=0;\n"
$vOut.="    while (lower(k,pListArray.length)) {\n"
$vOut.="      if (greater(pListArray[k].indexOf(\"#__co__#\") , 0)) {\n"
$vOut.="        var vSplitStep = pListArray[k].split(\"#__co__#\"); \n"
$vOut.="        vContent += \"<li>\";\n"
$vOut.="        vContent += \"[\"+vSplitStep[0]+\"] \"+decodeValue(vSplitStep[1]);\n"
$vOut.="        vContent +=\"</li>\";\n"
$vOut.="      }\n"
$vOut.="      k++;\n"
$vOut.="    };\n"
$vOut.="  }\n"
$vOut.="  return vContent;\n"
$vOut.="}\n"
$vOut.="function getItemsHTML(pList) {\n"
$vOut.="  var vContent = \"\";\n"
$vOut.="  if (pList) {\n"
$vOut.="    var k=0;\n"
$vOut.="    while (lower(k,pList.length)) {\n"
$vOut.="      if (pList[k].id) {\n"
$vOut.="        vContent += \"<li>\";\n"
$vOut.="        vContent += \"[\"+pList[k].id+\"] \"+decodeValue(pList[k].childNodes[0].nodeValue);\n"
$vOut.="        vContent +=\"</li>\";\n"
$vOut.="      }\n"
$vOut.="      k++;\n"
$vOut.="    };\n"
$vOut.="  }\n"
$vOut.="  return vContent;\n"
$vOut.="}\n"
$vOut.="function getStepIndex4ID(pID) {\n"
$vOut.="  var vListID    = document.getElementsByClassName(\"inSTEPID\"+vQID);\n"
$vOut.="  var i = 0;\n"
$vOut.="  var vIndex = -1;\n"
$vOut.="  while (lower(i,vListID.length)) {\n"
$vOut.="    if (pID == vListID[i].value) {\n"
$vOut.="      vIndex = i+1;\n"
$vOut.="    };\n"
$vOut.="    i++;\n"
$vOut.="  };\n"
$vOut.="  return vIndex;\n"
$vOut.="}\n"
$vOut.="function loadInput2IMathAS()  {\n"
$vOut.="  loadSteps2IMathAS(\"PRECONDITION\",\"qn\"+ThisQ+\"003\"); \n"
$vOut.="  loadSteps2IMathAS(\"CONCLUSION\",\"qn\"+ThisQ+\"004\"); \n"
$vOut.="  loadSteps2IMathAS(\"JUSTIFICATION\",\"qn\"+ThisQ+\"005\"); \n"
$vOut.="  loadSteps2IMathAS(\"PROOFSTEP\",\"qn\"+ThisQ+\"006\"); \n"
$vOut.="}\n"
$vOut.="function saveInput2IMathAS()  {\n"
$vOut.="  saveStepCount2IMathAS(\"iMathAS Steps Visible\",\"qn\"+ThisQ+\"000\");\n"
$vOut.="  saveDisplayOption2IMathAS(\"DISPLAYOPTION\"+vQID,\"qn\"+ThisQ+\"001\");\n"
$vOut.="  saveAnswer2IMathAS(\"STUDENTANSWER\",\"qn\"+ThisQ+\"002\");\n"
$vOut.="  saveSteps2IMathAS(\"PRECONDITION\",\"qn\"+ThisQ+\"003\"); \n"
$vOut.="  saveSteps2IMathAS(\"CONCLUSION\",\"qn\"+ThisQ+\"004\"); \n"
$vOut.="  saveSteps2IMathAS(\"JUSTIFICATION\",\"qn\"+ThisQ+\"005\"); \n"
$vOut.="  saveSteps2IMathAS(\"PROOFSTEP\",\"qn\"+ThisQ+\"006\"); \n"
$vOut.="}\n"
$vOut.="function loadStepCount2IMathAS(pLabel,pIMathAS_ID) {\n"
$vOut.="  var vNode = createNodeQN(pLabel,pIMathAS_ID);\n"
$vOut.="  var eProofInput = document.getElementById(\"sSTEPCOUNT\"+vQID);\n"
$vOut.="  var vInput = document.getElementById(\"imathSTEPCOUNT\"+vQID);\n"
$vOut.="  var vCount = vNode.value;\n"
$vOut.="  if (!vInput) {\n"
$vOut.="    vInput = createNodeQN(\"imathSTEPCOUNT\",\"imathSTEPCOUNT\"+vQID);\n"
$vOut.="  };\n"
$vOut.="  vInput.value = vCount;\n"
$vOut.="  if (eProofInput) {\n"
$vOut.="    eProofInput.value = parseInt(vCount+\"\");\n"
$vOut.="  } else {\n"
$vOut.="    alert(\"sSTEPCOUNT\"+vQID+\" is undefined\");\n"
$vOut.="  };\n"
$vOut.="}\n"
$vOut.="function saveStepCount2IMathAS(pLabel,pIMathAS_ID) {\n"
$vOut.="  var vListNode     = document.getElementsByClassName(\"STUDENTANSWER\"+vQID);\n"
$vOut.="  var vCount        = vListNode.length;\n"
$vOut.="  var vUnused = document.getElementById(\"UNUSEDSTEPS\"+vQID);\n"
$vOut.="  var vUnused4Proof = vUnused.getElementsByClassName(\"STUDENTANSWER\"+vQID);\n"
$vOut.="  var vCountUnused  = vUnused4Proof.length;\n"
$vOut.="    var vCountProof   = vListNode.length - vCountUnused;\n"
$vOut.="  var vStepCountNode = createNodeQN(\"(\"+pLabel+\")\",pIMathAS_ID);\n"
$vOut.="  var imathStepCountNode = document.getElementById(\"imathSTEPCOUNT\"+vQID);\n"
$vOut.="  if (imathStepCountNode) {\n"
$vOut.="    imathStepCountNode.value = vCountProof;\n"
$vOut.="  };\n"
$vOut.="  vStepCountNode.value = vCountProof;\n"
$vOut.="}\n"
$vOut.="function loadDisplayOption2IMathAS(pLabel,pIMathAS_ID) {\n"
$vOut.="  var vDisplaySelector = document.getElementById(\"sDISPLAYOPTION\"+vQID);\n"
$vOut.="  var vIMathNode = createNodeQN(\"(\"+pLabel+\")\",pIMathAS_ID);\n"
$vOut.="  var vEProofNode = document.getElementById(\"imathDISPLAYOPTION\"+vQID);\n"
$vOut.="  if (vEProofNode) {\n"
$vOut.="    vDisplaySelector.value = vEProofNode.value;\n"
$vOut.="  } else if (vIMathNode) {\n"
$vOut.="    vDisplaySelector.value = vIMathNode.value;\n"
$vOut.="  } else {\n"
$vOut.="    alert(\"sDISPLAYOPTION\"+vQID+ \" and imathDISPLAYOPTION\"+vQID+\" do not exist!\");\n"
$vOut.="  }\n"
$vOut.="}\n"
$vOut.="function saveDisplayOption2IMathAS(pLabel,pIMathAS_ID) {\n"
$vOut.="  var vDisplaySelector = document.getElementById(\"sDISPLAYOPTION\"+vQID);\n"
$vOut.="  var vIMathNode = createNodeQN(\"(\"+pLabel+\")\",pIMathAS_ID);\n"
$vOut.="  vIMathNode.value = vDisplaySelector.value;\n"
$vOut.="}\n"
$vOut.="function loadSteps2IMathAS(pClassName,pIMathAS_ID) {\n"
$vOut.="  var vInputNode = createNodeQN(\"(\"+pClassName+\")\",pIMathAS_ID);\n"
$vOut.="  var vTextArea = document.getElementById(\"imath\"+pClassName+vQID);\n"
$vOut.="  var vRootNode = document.getElementById(pClassName+\"LIST\"+vQID);\n"
$vOut.="  var vStepNode = null;\n"
$vOut.="  var vTextNode = null;\n"
$vOut.="  var vListArray = vTextArea.value.split(CR);\n"
$vOut.="  var k=0;\n"
$vOut.="  var vNr = 0;\n"
$vOut.="  while (lower(k,vListArray.length)) { \n"
$vOut.="    if (greater(vListArray[vNr].indexOf(\"#__co__#\") , 0)) {\n"
$vOut.="      var vStepArray = vListArray[vNr].split(\"#__co__#\") ;\n"
$vOut.="      var vStepDef = convertMeta2Comma(vStepArray[1]);\n"
$vOut.="      if (vStepArray.length != 2) alert(\"Wrong Format Answer Step='\"+vListArray[vNr]+\"'\");\n"
$vOut.="      vStepNode = document.getElementById(vStepArray[0]);\n"
$vOut.="      if (!vStepNode) {\n"
$vOut.="        vStepNode = document.createElement(\"DIV\");\n"
$vOut.="        vStepNode.className = pClassName+vQID;\n"
$vOut.="        vStepNode.id = vStepArray[0];\n"
$vOut.="        vTextNode = document.createTextNode(vStepDef);\n"
$vOut.="        vStepNode.appendChild(vTextNode);\n"
$vOut.="        vRootNode.appendChild(vStepNode);\n"
$vOut.="      } else {\n"
$vOut.="        vStepNode.innerHTML = vStepDef;\n"
$vOut.="      };\n"
$vOut.="      vNr++;\n"
$vOut.="    };\n"
$vOut.="    k++;\n"
$vOut.="  };\n"
$vOut.="}\n"
$vOut.="function saveSteps2IMathAS(pID,pIMathAS_ID) {\n"
$vOut.="  var vList = document.getElementsByClassName(pID+vQID);\n"
$vOut.="  var vTextArea = document.getElementById(\"imath\"+pID+vQID);\n"
$vOut.="  var vCR = \"\";\n"
$vOut.="  var vContent = \"\";\n"
$vOut.="  var vStepDef = \"\";\n"
$vOut.="  var k=0;\n"
$vOut.="  while (lower(k,vList.length)) { \n"
$vOut.="    vStepDef = convertComma2Meta(vList[k].childNodes[0].nodeValue);\n"
$vOut.="    vContent += vCR + vList[k].id+\"#__co__#\"+vStepDef;\n"
$vOut.="    vCR = CR;\n"
$vOut.="    k++;\n"
$vOut.="  };\n"
$vOut.="  vTextArea.value = vContent;\n"
$vOut.="  var vValue = encodeCR(vContent);\n"
$vOut.="  vInputNode = createNodeQN(\"(\"+pID+\")\",pIMathAS_ID);\n"
$vOut.="  vInputNode.value = vValue;\n"
$vOut.="}\n"
$vOut.="function loadAnswer2IMathAS(pID,pIMathAS_ID) {\n"
$vOut.="  var vListID = document.getElementsByClassName(\"inSTEPID\"+vQID);\n"
$vOut.="  var vList = document.getElementsByClassName(\"STUDENTANSWER\"+vQID);\n"
$vOut.="  var vInputNode = document.getElementById(\"imathSTUDENTANSWER\"+vQID);\n"
$vOut.="  vOutArray = vInputNode.value.split(CR);\n"
$vOut.="  var vAllSteps = getAllStepIDs();\n"
$vOut.="  var k=0;\n"
$vOut.="  var vLine = \"\";\n"
$vOut.="  var vStep = 0;\n"
$vOut.="  var vMove2Step = 0;\n"
$vOut.="  var vNode = null;\n"
$vOut.="  var vNr = 0\n"
$vOut.="  while (lower(k,vOutArray.length)) {\n"
$vOut.="    if (greater(vOutArray[k].indexOf(\"#__co__#\") , 0)) {\n"
$vOut.="      vLine = vOutArray[k];\n"
$vOut.="      vAnswerArray = vLine.split(\"#__co__#\");\n"
$vOut.="      if (vAnswerArray.length != 3) {\n"
$vOut.="        alert(\"Answer Array for Line\"+k+\" has no proper format!\"+CR+vOutArray[k]);\n"
$vOut.="      } else {\n"
$vOut.="        vNr++;\n"
$vOut.="        vStep = vNr;\n"
$vOut.="        var vID = vAnswerArray[1];\n"
$vOut.="        vNode = document.getElementById(\"sCONNECTION\"+vQID+vStep);\n"
$vOut.="        if (vAnswerArray[0] == \"???\") {\n"
$vOut.="          vNode.value = 0;\n"
$vOut.="        } else {\n"
$vOut.="          vNode.value = vConnection2Index[vAnswerArray[0]];\n"
$vOut.="        };\n"
$vOut.="        vNode = document.getElementById(\"inSTEPID\"+vQID+vStep);\n"
$vOut.="        vNode.value = vID;\n"
$vOut.="        vNode = document.getElementById(\"sSTEP\"+vQID+vStep);\n"
$vOut.="        vNode.value = vID;\n"
$vOut.="        vNode = document.getElementById(\"inSTEPDEF\"+vQID+vStep);\n"
$vOut.="        vNode.value = vAllSteps[vAnswerArray[1]];\n"
$vOut.="        vNode = document.getElementById(\"inJUSTIFICATION\"+vQID+vStep);\n"
$vOut.="        vNode.value = vAnswerArray[2].replace(/#_co_#/g,\",\");\n"
$vOut.="        updateStep(vStep);\n"
$vOut.="        setJustificationCheckbox(vStep);\n"
$vOut.="        showSelectedJustifications(vStep);\n"
$vOut.="      };\n"
$vOut.="    };\n"
$vOut.="    k++;\n"
$vOut.="  };  \n"
$vOut.="}\n"
$vOut.="function saveAnswer2IMathAS(pID,pIMathAS_ID) {\n"
$vOut.="  var vOutArray = new Array();\n"
$vOut.="  var vList = document.getElementsByClassName(\"STUDENTANSWER\"+vQID);\n"
$vOut.="  var vPosList  = document.getElementsByClassName(\"sPOSITION\"+vQID);\n"
$vOut.="  var vConList  = document.getElementsByClassName(\"sCONNECTION\"+vQID);\n"
$vOut.="  var vIDList   = document.getElementsByClassName(\"sSTEP\"+vQID);\n"
$vOut.="  var vJustList = document.getElementsByClassName(\"inJUSTIFICATION\"+vQID);\n"
$vOut.="  var vOutTextarea = document.getElementById(\"imathSTUDENTANSWER\"+vQID);\n"
$vOut.="  var vOutString = \"\";\n"
$vOut.="  var vStepSplit = CR;\n"
$vOut.="  var vColSplit = \"#__co__#\"\n"
$vOut.="  var vJustSplit = \"#_co_#\"\n"
$vOut.="  var vStepNode = null;\n"
$vOut.="  var vJustification = \"\";\n"
$vOut.="  var vPos,vIndex = 0;\n"
$vOut.="  var vPosNode = null;\n"
$vOut.="  var vID = \"???\";\n"
$vOut.="  var k=0;\n"
$vOut.="  var vMax = 0;\n"
$vOut.="  while (lower(k,vList.length)) {\n"
$vOut.="    vOutString = \"\";\n"
$vOut.="    if (vList[k].id) {\n"
$vOut.="      vStep = getStep4NodeID(vList[k].id);\n"
$vOut.="      vIndex = vConList[k].value;\n"
$vOut.="      vOutString += vConnectionArray[parseInt(\" \"+vIndex)];\n"
$vOut.="      vOutString += vColSplit;\n"
$vOut.="      vID = vIDList[k].value;\n"
$vOut.="      vOutString += vID + vColSplit;\n"
$vOut.="      vJustification =vJustList[k].value;\n"
$vOut.="      vOutString += vJustification.replace(/,/g,vJustSplit);\n"
$vOut.="      vOutArray.push(vOutString);\n"
$vOut.="    }\n"
$vOut.="    k++;\n"
$vOut.="  }\n"
$vOut.="  vOutTextarea.value = vOutArray.join(vStepSplit);\n"
$vOut.="  vInputNode = createNodeQN(\"(\"+pID+\")\",pIMathAS_ID);\n"
$vOut.="  vInputNode.value = vOutArray.join(\",\");\n"
$vOut.="}\n"
$vOut.="function getStep4NodeID(pID) {\n"
$vOut.="  var vStep = 0;\n"
$vOut.="  if (pID) {\n"
$vOut.="    pID = pID.replace(vQID,\"\");\n"
$vOut.="    var vStep = pID.replace(/[^0-9]/g,\"\");\n"
$vOut.="    vStep = parseInt(vStep);\n"
$vOut.="  };\n"
$vOut.="  return vStep;  \n"
$vOut.="}\n"
$vOut.="function getElementQN(pStep,pCol)  {\n"
$vOut.="  var vNameQN = getFormElementName(pStep,pCol);\n"
$vOut.="  var vReturnNode = createNodeQN(\"(S\"+pStep+\"C\"+pCol+\")\",vNameQN);\n"
$vOut.="    return vReturnNode;\n"
$vOut.="}\n"
$vOut.="function createNodeQN(pLabel,pNameQN)  {\n"
$vOut.="  var vReturnNode = document.getElementById(pNameQN);\n"
$vOut.="  if (!vReturnNode) {\n"
$vOut.="    var vReturnNode = document.createElement(\"input\");\n"
$vOut.="    var vParent = document.getElementById(\"iMathASINOUT\"+vQID);\n"
$vOut.="    vReturnNode.type = \"text\";\n"
$vOut.="    vReturnNode.name = pNameQN;\n"
$vOut.="    vReturnNode.id   = pNameQN;\n"
$vOut.="    vReturnNode.size = \"8\";\n"
$vOut.="    var vLabelNode = document.createTextNode(pLabel+\" \"+pNameQN +\":\");\n"
$vOut.="    var vBR = document.createElement(\"hr\");\n"
$vOut.="    if(greater(pLabel.indexOf(\"C0)\"),0)) vParent.appendChild(vBR);\n"
$vOut.="    vParent.appendChild(vLabelNode);\n"
$vOut.="    vParent.appendChild(vReturnNode);\n"
$vOut.="   };\n"
$vOut.="     return vReturnNode;    \n"
$vOut.="} \n"
$vOut.="function updateStepCount(pCount)  {\n"
$vOut.="  var vListNode    = document.getElementsByClassName(\"STUDENTANSWER\"+vQID);\n"
$vOut.="  var vProof       = document.getElementById(\"STUDENTANSWERLIST\"+vQID);\n"
$vOut.="  var vUnused      = document.getElementById(\"UNUSEDSTEPS\"+vQID);\n"
$vOut.="  var  vUnusedCount = 0;\n"
$vOut.="  var vRemovedChild = null; \n"
$vOut.="  var k=0;\n"
$vOut.="  while (lower(k,vListNode.length)) {\n"
$vOut.="    if(vListNode[k].parentNode.id == \"UNUSEDSTEPS\"+vQID) {\n"
$vOut.="      vUnusedCount++;\n"
$vOut.="    };\n"
$vOut.="    k++;\n"
$vOut.="  };\n"
$vOut.="  var vProofCount  = vListNode.length - vUnusedCount;\n"
$vOut.="  vProofCount = vListNode.length - vUnusedCount;\n"
$vOut.="  if (lower(pCount,vProofCount)) {\n"
$vOut.="    while (lower(pCount,vProofCount)) {\n"
$vOut.="      vRemovedChild = vProof.removeChild(vListNode[pCount-1]);\n"
$vOut.="       vUnused.insertBefore(vRemovedChild,vUnused.firstChild);\n"
$vOut.="      vProofCount--;\n"
$vOut.="    }  \n"
$vOut.="  } else if (greater(pCount , vProofCount)) {\n"
$vOut.="    while (lower(vProofCount,pCount)) {\n"
$vOut.="       vRemovedChild = vUnused.removeChild(vListNode[vProofCount]);\n"
$vOut.="       vProof.appendChild(vRemovedChild);\n"
$vOut.="      vProofCount++;\n"
$vOut.="    }  \n"
$vOut.="  };\n"
$vOut.="  setVisibility4Unused();\n"
$vOut.="  updateInput();\n"
$vOut.="}\n"
$vOut.="function decodeEditBox() {\n"
$vOut.="  var vListNode = document.getElementsByClassName(\"inSTEPDEF\"+vQID);\n"
$vOut.="  i=0;\n"
$vOut.="  while (lower(i,vListNode.length)) {\n"
$vOut.="    vListNode[i].value = decodeValue(vListNode[i].value);  \n"
$vOut.="    updateTextIDs(i+1);\n"
$vOut.="    i++;\n"
$vOut.="  };  \n"
$vOut.="}\n"
$vOut.="function showEditBox() {\n"
$vOut.="  var vID = \"\";\n"
$vOut.="  var vListNode = document.getElementsByClassName(\"inSTEPID\"+vQID);\n"
$vOut.="  var vAuthoringMode = getSetting(\"AuthoringMode\");\n"
$vOut.="  var i=0;\n"
$vOut.="  while (lower(i,vListNode.length)) {\n"
$vOut.="    vID = vListNode[i].value;\n"
$vOut.="    vID = vID.replace(/[^A-Z]/g,\"\");\n"
$vOut.="    if ((vID == \"MY\") || (vAuthoringMode+\"\" == \"1\")) { \n"
$vOut.="      showElement(\"bEdit\"+vQID+vListNode[i].step);\n"
$vOut.="    } else {\n"
$vOut.="      hideElement(\"bEdit\"+vQID+vListNode[i].step);\n"
$vOut.="    };\n"
$vOut.="    i++;\n"
$vOut.="  };  \n"
$vOut.="}\n"
$vOut.="function convertComma2Meta(pString) {\n"
$vOut.="  return pString.replace(/,/g,\"#_co_#\");\n"
$vOut.="}\n"
$vOut.="function convertMeta2Comma(pString) {\n"
$vOut.="  return pString.replace(/#_co_#/g,\",\");\n"
$vOut.="}\n"
$vOut.="function decodeValue(pValue) {\n"
$vOut.="  if (pValue) {\n"
$vOut.="    pValue = pValue.replace(/__math__/g,AP);\n"
$vOut.="    pValue = pValue.replace(/__eq__/g,\"=\");\n"
$vOut.="    eval(\"pValue = pValue.replace(/__gt__/g,\\\"\"+GT+\"\\\");\");\n"
$vOut.="    eval(\"pValue = pValue.replace(/__lt__/g,\\\"\"+LT+\"\\\");\");\n"
$vOut.="    pValue = pValue.replace(/__qu__/g,\"\\\"\");\n"
$vOut.="    pValue = pValue.replace(/__ae__/g,\"ä\");\n"
$vOut.="    pValue = pValue.replace(/__oe__/g,\"ö\");\n"
$vOut.="    pValue = pValue.replace(/__ue__/g,\"ü\");\n"
$vOut.="    pValue = pValue.replace(/__AE__/g,\"Ä\");\n"
$vOut.="    pValue = pValue.replace(/__OE__/g,\"Ö\");\n"
$vOut.="    eval(decodeURI(\"pValue=pValue.replace(/__OE__/g,%22%EF%BF%BD%22);\"))\n"
$vOut.="    pValue = pValue.replace(/__UE__/g,\"Ü\");\n"
$vOut.="    pValue = pValue.replace(/__sz__/g,\"ß\");\n"
$vOut.="    return pValue;\n"
$vOut.="    } else {\n"
$vOut.="      return \"\";\n"
$vOut.="    }\n"
$vOut.="}\n"
$vOut.="function encodeCR(pValue) {\n"
$vOut.="  eval(decodeURI(\"pValue=pValue.replace(/%5Cn/g,%22,%22)\"));\n"
$vOut.="  return pValue;\n"
$vOut.="}\n"
$vOut.="function decodeCR(pValue) {\n"
$vOut.="  pValue = pValue.replace(/,/g,CR);\n"
$vOut.="  return pValue;\n"
$vOut.="}\n"
$vOut.="function decodeTextarea(pValue) {\n"
$vOut.="  pValue = decodeValue(pValue);\n"
$vOut.="  pValue = pValue.replace(/__n__/g,CR);\n"
$vOut.="  return pValue;\n"
$vOut.="}      \n"
$vOut.="function encodeValue(pValue) {\n"
$vOut.="  if (pValue) {\n"
$vOut.="    eval(\"pValue = pValue.replace(/\"+AP+\"/g,\\\"__math__\\\")\");\n"
$vOut.="    eval(\"pValue = pValue.replace(/\"+LT+\"/g,\\\"__lt__\\\")\");\n"
$vOut.="    eval(\"pValue = pValue.replace(/\"+GT+\"/g,\\\"__gt__\\\")\");\n"
$vOut.="    pValue = pValue.replace(/=/g,\"__eq__\");\n"
$vOut.="    pValue = pValue.replace(/\"/g,\"__qu__\");\n"
$vOut.="    pValue = pValue.replace(/ä/g,\"__ae__\");\n"
$vOut.="    pValue = pValue.replace(/ö/g,\"__oe__\");\n"
$vOut.="    pValue = pValue.replace(/ü/g,\"__ue__\");\n"
$vOut.="    pValue = pValue.replace(/Ä/g,\"__AE__\");\n"
$vOut.="    eval(decodeURI(\"pValue%20=%20pValue.replace(/%EF%BF%BD/g,%22__OE__%22);\"));\n"
$vOut.="    pValue = pValue.replace(/Ü/g,\"__UE__\");\n"
$vOut.="    pValue = pValue.replace(/ß/g,\"__sz__\");\n"
$vOut.="    return pValue;\n"
$vOut.="    } else {\n"
$vOut.="      return \"\";\n"
$vOut.="    }\n"
$vOut.="}\n"
$vOut.="function getSetting(pID) {\n"
$vOut.="  return vSettings[pID];\n"
$vOut.="}\n"
$vOut.="function getFormElementName(pStep,pCol) {\n"
$vOut.="  var vNr = 1004 + 6 * pStep + pCol;\n"
$vOut.="  return \"qn\"+vNr;\n"
$vOut.="}\n"
$vOut.="function setNumberOfSteps() {\n"
$vOut.="  var vNode = createNodeQN(\"Step COUNT\",\"qn\"+ThisQ+\"000\");\n"
$vOut.="  var vNodeIMath = createNodeQN(\"imathSTEPCOUNT\",\"imathSTEPCOUNT\"+vQID);\n"
$vOut.="  var vInput = document.getElementById(\"sSTEPCOUNT\"+vQID);\n"
$vOut.="  vNodeIMath.value = vInput.value;\n"
$vOut.="  vNode.value = vInput.value; \n"
$vOut.="  saveInput2IMathAS();\n"
$vOut.="}\n"
$vOut.="function postProcessProof() {\n"
$vOut.="  loadStepCount2IMathAS(\"iMathAS Steps Visible\",\"imathSTEPCOUNT\"+vQID);\n"
$vOut.="  loadAnswer2IMathAS('STUDENTANSWER'+vQID,'imathSTUDENTANSWER'+vQID);\n"
$vOut.="  loadDisplayOption2IMathAS(\"DISPLAYOPTION\"+vQID,\"imathSTEPCOUNT\"+vQID);\n"
$vOut.="  setDisplayOptions();\n"
$vOut.="  decodeEditBox();\n"
$vOut.="  showEditBox();\n"
$vOut.="  setVisibility4Unused()\n"
$vOut.="}\n"
$vOut.="\n"
//--------------------------------------------------------------
$eProofJS = $vOut
//--------------------------------------------------------------
//---END: eProofJS.js Generator---------------------------------
//--------------------------------------------------------------
